import mongoose from "mongoose";

const AddressSchema = new mongoose.Schema({
  division: { type: String },
  district: { type: String },
  rmo: { type: String },
  cityCorporation: { type: String },
  upozila: { type: String },
  unionWard: { type: String },
  mouzaMoholla: { type: String },
  additionalMouzaMoholla: { type: String },
  wardForUnionPorishod: { type: String },
  villageRoad: { type: String },
  additionalVillageRoad: { type: String },
  homeHolding: { type: String },
  postOffice: { type: String },
  postalCode: { type: String },
  region: { type: String },
});

const NIDDataSchema = new mongoose.Schema({
  citizen: { type: String, default: null },
  nationalId: { type: String, required: true },
  pin: { type: String, required: true },
  status: { type: String, default: null },
  afisStatus: { type: String, default: null },
  lockFlag: { type: String, default: null },
  voterNo: { type: String, default: null },
  formNo: { type: String, default: null },
  slNo: { type: String, default: null },
  tag: { type: String, default: null },
  nameBangla: { type: String, required: true },
  nameEnglish: { type: String, required: true },
  dateOfBirth: { type: String, required: true },
  birthPlace: { type: String, required: true },
  birthOther: { type: String, default: null },
  birthRegistration: { type: String, default: null },
  fatherName: { type: String, required: true },
  motherName: { type: String, required: true },
  spouseName: { type: String, default: null },
  gender: { type: String, default: null },
  marital: { type: String, default: null },
  occupation: { type: String, default: null },
  disability: { type: String, default: null },
  disabilityOther: { type: String, default: null },
  presentAddress: { type: AddressSchema, required: true },
  permanentAddress: { type: AddressSchema, required: true },
  education: { type: String, default: null },
  identification: { type: String, default: null },
  bloodGroup: { type: String, default: undefined },
  tin: { type: String, default: null },
  driving: { type: String, default: null },
  passport: { type: String, default: null },
  laptopId: { type: String, default: null },
  nidFather: { type: String, default: null },
  nidMother: { type: String, default: null },
  nidSpouse: { type: String, default: null },
  voterNoFather: { type: String, default: null },
  voterNoMother: { type: String, default: null },
  voterNoSpouse: { type: String, default: null },
  phone: { type: String, default: null },
  mobile: { type: String, default: null },
  religion: { type: String, default: null },
  religionOther: { type: String, default: null },
  noFinger: { type: String, default: null },
  noFingerPrint: { type: String, default: null },
  voterArea: { type: String, default: null },
  voterAt: { type: String, default: null },
  nidAddress: { type: String, default: null },
  userImage: { type: String },
  userSign: { type: String },
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
    required: true,
  },
});
NIDDataSchema.index({ nationalId: 1 });
NIDDataSchema.index({ pin: 1 });
const NIDData =
  mongoose.models.NIDData || mongoose.model("NIDData", NIDDataSchema);

export default NIDData;
