import express from "express";
import getAllNid from "../utils/helper/getAllNid.js";
import editNid from "../utils/helper/editNid.js";
import searchNid from "../utils/helper/searchNid.js";
import generateNid from "../utils/helper/generateNid.js";
const router = express.Router();
router.get("/all-nid", getAllNid);
router.post("/edit/:id", editNid);
router.get("/search", searchNid);
router.post("/generateNid", generateNid);
export default router;
