import express from "express";
import getAllNid from "../utils/helper/getAllNid.js";
// import editNid from "../utils/helper/editNid.js";
import searchNid from "../utils/helper/searchNid.js";
import generateNid from "../utils/helper/generateNid.js";
import { authenticateJWT } from "../utils/middleware/authenticate.js";
const router = express.Router();
router.get("/all-nid", authenticateJWT, getAllNid);
router.get("/search", authenticateJWT, searchNid);
router.post("/generateNid", authenticateJWT, generateNid);
export default router;
