
services:
  image_api:
    build: ./nodejs_image_extraction
    networks:
      - app_network
    env_file:
      - .env

  puppeteer_app:
    build: ./Nodejs_server
    depends_on:
      - mongo
      - python_app
      - image_api
    networks:
      - app_network
    env_file:
      - .env
    restart: always
    volumes:
      - ./Nodejs_server/htmlNidTemplate:/app/htmlNidTemplate
  
  python_app:
    build: ./Python_server
    networks:
      - app_network
    env_file:
      - .env

  admin:
    build: ./admin
    ports:
      - "3000:3000"
    networks:
      - app_network
    env_file:
      - .env

  mongo:
    image: mongo:5.0.10
    ports:
      - "27017:27017"
    networks:
      - app_network
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=biz

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
