
services:
  image_api:
    build: ./nodejs_image_extraction
    ports:
      - "4000:4000"
    networks:
      - app_network
    env_file:
      - .env

  puppeteer_app:
    build: ./Nodejs_server
    depends_on:
      - mongo
      - python_app
      - image_api
    networks:
      - app_network
    env_file:
      - .env
    restart: always
  
  python_app:
    build: ./Python_server
    ports:
      - "8000:8000"
    networks:
      - app_network
    env_file:
      - .env

  admin:
    build: ./admin
    ports:
      - "3000:3000"
    networks:
      - app_network
    env_file:
      - .env

  mongo:
    image: mongo:5.0.10
    ports:
      - "27017:27017"
    networks:
      - app_network
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
