# Stage 1: Build stage
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Set environment variable to skip Chromium download during build
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application files
COPY . .

# Compile TypeScript to JavaScript
RUN npm run build

# # Debug: Check if the build directory exists
# RUN ls -l /app/dist

# Stage 2: Production stage
FROM node:18-alpine

# Install Chromium and its dependencies
RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ca-certificates \
    ttf-freefont

# Set Puppeteer-specific environment variables
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser \
    NODE_ENV=production

# Set the working directory
WORKDIR /app

# Copy necessary files from the build stage
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/htmlNidTemplate ./htmlNidTemplate


# # Debug: Check if files are copied
# RUN ls -l /app/dist

# # Install production dependencies only
# RUN npm install --omit=dev

# Start the application
CMD ["node", "dist/index.js"]
