FROM python:3.11

WORKDIR /python_text_extractor

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY app.py app.py

CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "app:app"]

EXPOSE 8000
